# Generated by Django 4.2.5 on 2023-09-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse e-mail')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='Est enseignant')),
                ('is_student', models.BooleanField(default=False, verbose_name='Est étudiant')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nom de famille')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('country', models.CharField(max_length=255, verbose_name='Pays')),
                ('city', models.CharField(max_length=255, verbose_name='Ville')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
